# **Курс "Програмування на мові Python"**

##### Викладачі:
##### Борисенко Павло Борисович
##### Щьоголєв Максим Олегович


## **Практичне зайняття №8**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи перестановки та символ Леві-Чивіти.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажання можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools 

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix
def perm_matrix(num):
    """
    The function that finds all permutations
    """
    first_array = np.array([])
    second_array = []
    for i in range(1, num + 1):
        first_array = np.append(first_array, i)
    for i in itertools.permutations(first_array):
        array = list(i)
        second_array.append(array)
    array = second_array
    return array

def multiply(matrix, num, array):
    """
    The function that multiply all elements and add result to an array
    """
    claculation = np.array([])
    for i in range(factorial(num)):
        an = 1
        for j in range(num):
           an *= matrix[j][int(array[i][j]) - 1]
        an *= ((-1) ** inverse_matrix(array[i]))
        claculation = np.append(claculation, an)
    return claculation

def det(list,num):
    """
    The function that finds sum of multiplying functions
    """
    sum = 0
    for i in multiply(matrix, num, perm_matrix(num)):
        sum += int(i)
    return sum

def input_number(message):
    """
    The function that finds if user input right
    """
    while True:
        try:
            user_num = int(input(message))
            if user_num <= 0:
                raise ValueError("The number must be positive")
            return user_num
        except ValueError as ve:
            print(ve)

def factorial(num):
    """
    The function that finds factorial of a number
    """
    if num == 0:
        return 1
    return factorial(num - 1) * num

def inverse_matrix(list):
    """
    The function that inversing this matrix
    """
    invers = 0
    for i in list:
        for j in range(list.index(i), len(list)):
            if i > list[j]:
                invers += 1
    return invers
# input
dim = input_number("Input number: ")
matrix = random_matrix(dim)
result = det(multiply(matrix, dim, perm_matrix(dim)), dim)
#print result
print("Determinant of matrix:")
print(matrix)
print("Equals:", result)

The number must be positive
invalid literal for int() with base 10: 'w'
Determinant of matrix:
[[1 2 4 6 2]
 [5 5 7 1 9]
 [1 8 6 0 0]
 [1 8 2 8 8]
 [8 7 9 2 5]]
Equals: -15680
